name: Mall Web CI

on:
  pull_request:
    branches: [ develop, master ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    name: Mall Web Build
    runs-on: ubuntu-latest

    steps:

      - name: Check Out Branch
        uses: actions/checkout@v2

      - name: Setup Node Server
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Cache Node Dependencies
        id: cache-npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install
        working-directory: .

      - name: Build Web
        run: npm run build
